version: '3.7'

services:
  db:
    image: library/postgres:14.1-alpine3.15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=shoppp
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=shoppp
    ports:
      - 5432:5432
  web:
    build: ""
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code/
    ports:
      - 8000:8000
    env_file:
      - .env.dev
    depends_on:
      - db


volumes:
  postgres_data: